// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/ats/simulation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ats/simulation">> = Specific
  const handler = {} as typeof import("../../src/app/ats/simulation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ats/simulation/report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ats/simulation/report">> = Specific
  const handler = {} as typeof import("../../src/app/ats/simulation/report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/drd/datasetting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/drd/datasetting">> = Specific
  const handler = {} as typeof import("../../src/app/drd/datasetting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/drd/default-setting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/drd/default-setting">> = Specific
  const handler = {} as typeof import("../../src/app/drd/default-setting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/drd/filter/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/drd/filter">> = Specific
  const handler = {} as typeof import("../../src/app/drd/filter/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/drd/high-risk-subgroup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/drd/high-risk-subgroup">> = Specific
  const handler = {} as typeof import("../../src/app/drd/high-risk-subgroup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/drd/medical-history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/drd/medical-history">> = Specific
  const handler = {} as typeof import("../../src/app/drd/medical-history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/drd/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/drd">> = Specific
  const handler = {} as typeof import("../../src/app/drd/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/drd/patient-disease-info/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/drd/patient-disease-info">> = Specific
  const handler = {} as typeof import("../../src/app/drd/patient-disease-info/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/drd/simulation-condition/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/drd/simulation-condition">> = Specific
  const handler = {} as typeof import("../../src/app/drd/simulation-condition/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/drd/simulation-result/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/drd/simulation-result">> = Specific
  const handler = {} as typeof import("../../src/app/drd/simulation-result/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/drd/simulation-setting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/drd/simulation-setting">> = Specific
  const handler = {} as typeof import("../../src/app/drd/simulation-setting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/drd/smile-setting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/drd/smile-setting">> = Specific
  const handler = {} as typeof import("../../src/app/drd/smile-setting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tsi/basis-selection/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tsi/basis-selection">> = Specific
  const handler = {} as typeof import("../../src/app/tsi/basis-selection/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tsi/filter/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tsi/filter">> = Specific
  const handler = {} as typeof import("../../src/app/tsi/filter/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tsi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tsi">> = Specific
  const handler = {} as typeof import("../../src/app/tsi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tsi/patients-summary/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tsi/patients-summary">> = Specific
  const handler = {} as typeof import("../../src/app/tsi/patients-summary/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tsi/refine-cutoffs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tsi/refine-cutoffs">> = Specific
  const handler = {} as typeof import("../../src/app/tsi/refine-cutoffs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tsi/report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tsi/report">> = Specific
  const handler = {} as typeof import("../../src/app/tsi/report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tsi/subgroup-explain/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tsi/subgroup-explain">> = Specific
  const handler = {} as typeof import("../../src/app/tsi/subgroup-explain/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tsi/subgroup-selection/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tsi/subgroup-selection">> = Specific
  const handler = {} as typeof import("../../src/app/tsi/subgroup-selection/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/proxy/download/[taskId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/proxy/download/[taskId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/proxy/download/[taskId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/proxy/study-play/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/proxy/study-play">> = Specific
  const handler = {} as typeof import("../../src/app/api/proxy/study-play/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
